import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";
import styles from "@/styles/components/layout.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Banda Neira",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className={styles.nav}>
          <div className={styles.navLogo}>
            <Link href="/">
              <Image src="/image/logo.png" alt="Logo" width={50} height={50} />
            </Link>
          </div>
          <ul className={styles.navLink}>
            <li>
              <Link href="/" className={styles.navLink}>
                Home
              </Link>
            </li>
            <li className={styles.navItem}>
              <Link href="/destinations" className={styles.navLink}>
                Destinations
              </Link>
            </li>
            <li className={styles.navItem}>
              <Link href="/culinary" className={styles.navLink}>
                Culinary
              </Link>
            </li>
            <li className={styles.navItem}>
              <Link href="/culture" className={styles.navLink}>
                Culture
              </Link>
            </li>
            <li className={styles.navItem}>
              <Link href="/contact" className={styles.navLink}>
                Contact Us
              </Link>
            </li>
          </ul>
        </nav>
        {children}
        <footer className={styles.footer}>
          <p>© 2025 Zann. Banda Neira.</p>
        </footer>
      </body>
    </html>
  );
}
